version: '3.6'

services:
  web:
    image: nginx
    ports:
      - "8080:80"

  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: victus_test_db
      MYSQL_USER: victus
      MYSQL_PASSWORD: victus
